// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbyeednwkfmiajwzwdzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdieWVlZG53a2ZtaWFqd3p3ZHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTQ0OTAsImV4cCI6MjA2NjI3MDQ5MH0.PXq121-5eVRFsb8WXecMZ1L92nSdb3oPafKB0LPJoM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);